#!/bin/bash --login

TOOLS=/work/projects/melanomics/tools
PATH=$TOOLS/breakfast/pypette-0.7.1/bin/:$PATH
PATH=$TOOLS/breakfast/pypy-2.2.1-linux_x86_64-portable/bin/:$PATH
PATH=$TOOLS/bowtie/bowtie-1.0.0/:$PATH
PATH=$TOOLS/samtools/samtools:$PATH
export PATH
